spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: your-email@gmail.com
#    password: your-password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lhjhoon@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true
        debug: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


jwt:
  secret-key: LeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJLeeHJ
  period: 86_400_000